const express = require("express");
const interviewRouter = express.Router();


const authMiddleware = require("../middlewares/auth.middleware")
const interviewController = require("../controllers/interview.controller")
const upload = require("../middlewares/file.middleware");

/**
 * @route POST /api/interview/generateReport
 * @desc Generate interview report based on candidate's resume, self description and job description
 * @access Private
 */
interviewRouter.post("/",authMiddleware.authUser ,upload.single("resume") ,interviewController.generateReportController)


/**
 * @route GET /api/interview/:interviewId
 * @desc Get interview report by ID
 * @access Private
 */
interviewRouter.get("/report/:interviewId", authMiddleware.authUser, interviewController.getInterviewReportByIdController)


/**
 * @route GET /api/interview/
 * @desc Get all interview reports of the logged in user
 * @access Private
 */
interviewRouter.get("/", authMiddleware.authUser, interviewController.getAllInterviewReportsController)  

/**
 * @route GET /api/interview/downloadResume/:interviewId
 * @desc Download resume PDF generated by AI for the interview report
 * @access Private
 */
interviewRouter.get("/resume/pdf/:interviewReportId", authMiddleware.authUser, interviewController.generateResumePdfController)


module.exports = interviewRouter;